apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/backend
- ../base/mysql

namespace: dev

labels:
- includeSelectors: true
  pairs:
    env: dev
images:
- name: paulernestcloud/k8s-gitops
  newName: 5b6d24a2f09bad9a23c317e7c9c91c363ba3413c
