apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/backend
  - ../base/mysql

namespace: dev

labels:
  - includeSelectors: true
    pairs:
      env: dev
images:
  - name: paulernestcloud/k8s-gitops
    newName: paulernestcloud/k8s-gitops
    newTag: f9210b88bb0d885b3e52f58e45adea29f091e54a
