# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Push Backend

permissions:
  contents: write

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: paulernestcloud/k8s-gitops:${{ github.sha }}

      - name: Update Kustomize Image
        run: |
          cd k8s/dev
          kustomize edit set image paulernestcloud/k8s-gitops=${{ github.sha }}
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add kustomization.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push
